World:
	LuaScript:
		Scripts: script.lua
	-CrateSpawner:
	MapOptions:
		ShortGameEnabled: True
	SpawnMPUnits:
		StartingUnitsClass: nexus
	MapBuildRadius:
		AllyBuildRadiusEnabled: False
	MPStartUnits@nexus:
		Class: nexus
		Factions: gdi, nod
		BaseActor: mcv
		ClassName: Special Nexus Start	
	-MPStartUnits@mcvonly:
	-MPStartUnits@defaultgdia:
	-MPStartUnits@defaultnoda:
	-MPStartUnits@heavynoda:
	-MPStartUnits@heavynodb:
	-MPStartUnits@heavygdia:
	-MPStartUnits@heavygdib:

	
^Palettes:
	PaletteFromFile@RA:
		Name: ra
		Filename: temperatRA.pal
		ShadowIndex: 4
	PaletteFromFile@RA_EFFECT:
		Name: ra_effect
		Filename: temperatRA.pal
		ShadowIndex: 4
	PlayerColorPalette@RA:
		BasePalette: ra
		BaseName: raplayer
		RemapIndex: 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95



